GET http://localhost:5008/games

###

GET http://localhost:5008/getGamesById/3

###

POST http://localhost:5008/games
Content-Type: application/json

{
    "Name":"Game 5",
    "genreId":3,
    "price":19.99,
    "ReleseDate":"2011-11-8"
}


###

PUT http://localhost:5008/games/1
Content-Type: application/json

{
    "Name": " New Game 1",
    "Genre": "Science",
    "price": 29.99,
    "ReleaseDate": "1998-07-15"
}

###

DELETE http://localhost:5008/games/2